# Generated by Django 4.2.7 on 2023-11-22 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=30, unique=True)),
                ('long_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etype', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=2)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ledger.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='ledger.currency')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ledger.classification')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ledger.classification'),
        ),
    ]
