# Generated by Django 4.2.7 on 2023-11-24 20:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='classification',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classification',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='children', to='ledger.classification'),
        ),
        migrations.CreateModel(
            name='ImportedEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField()),
                ('data', models.JSONField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ledger.importtask')),
                ('transaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ledger.transaction')),
            ],
            options={
                'ordering': ['task', 'serial'],
                'unique_together': {('task', 'serial')},
            },
        ),
    ]
