# Generated by Django 4.2.7 on 2023-11-24 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_importtask_alter_account_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importtask',
            name='fieldnames',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='importedentry',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.importtask'),
        ),
    ]
