# Generated by Django 4.2.7 on 2023-11-25 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_importtask_fieldnames_alter_importedentry_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='entry',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.transaction'),
        ),
    ]
