# Generated by Django 4.2.7 on 2023-11-25 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_period_alter_entry_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='period',
            field=models.ForeignKey(default='2023', on_delete=django.db.models.deletion.RESTRICT, to='ledger.period'),
            preserve_default=False,
        ),
    ]
